# Generated by Django 5.1 on 2024-10-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumables', '0002_alter_consumable_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consumable',
            table='consumables',
        ),
    ]
