# Generated by Django 5.1 on 2024-10-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumables', '0003_alter_consumable_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/consumables/'),
        ),
    ]
