# Generated by Django 5.1 on 2024-10-29 17:09

import consumables.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumables', '0004_alter_consumable_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=consumables.models.image_upload_path),
        ),
    ]
